language: python
python:
  - "2.7"
install:
  - "pip install tox"
  - "curl -L  https://github.com/coreos/etcd/releases/download/v2.3.3/etcd-v2.3.3-linux-amd64.tar.gz -o etcd-v2.3.3-linux-amd64.tar.gz && tar xvzf etcd-v2.3.3-linux-amd64.tar.gz"
script:
  - "tox -v -e py27"
  - "PATH=$PATH:`pwd`/etcd-v2.3.3-linux-amd64 tox -v -e e2e"
notifications:
  email: false
  # This is Colin's instance of Homu, in the future
  # we'll move this to a production cluster.
  webhooks: http://escher.verbum.org:54856/travis
